"""Initial migration

Revision ID: 3e520abd752a
Revises: 
Create Date: 2026-01-22 21:25:27.860951

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '3e520abd752a'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('certification_levels', 'level_name',
               existing_type=sa.VARCHAR(length=100),
               type_=sa.String(length=50),
               existing_nullable=False)
    op.alter_column('certification_levels', 'level_type',
               existing_type=sa.VARCHAR(length=20),
               nullable=True)
    op.alter_column('certification_levels', 'description',
               existing_type=sa.TEXT(),
               type_=sa.String(length=255),
               existing_nullable=True)
    op.alter_column('certification_levels', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
    op.create_index(op.f('ix_certification_levels_id'), 'certification_levels', ['id'], unique=False)
    op.drop_table_comment(
        'certification_levels',
        existing_comment='Reference table for coach and umpire certification levels',
        schema=None
    )
    op.alter_column('clubs', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
    op.alter_column('clubs', 'updated_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
    op.drop_constraint(op.f('clubs_slug_key'), 'clubs', type_='unique')
    op.drop_index(op.f('idx_clubs_deleted_at'), table_name='clubs')
    op.drop_index(op.f('idx_clubs_head_coach_id'), table_name='clubs')
    op.drop_index(op.f('idx_clubs_slug'), table_name='clubs')
    op.create_index(op.f('ix_clubs_id'), 'clubs', ['id'], unique=False)
    op.create_index(op.f('ix_clubs_slug'), 'clubs', ['slug'], unique=True)
    op.drop_constraint(op.f('fk_clubs_head_coach'), 'clubs', type_='foreignkey')
    op.drop_table_comment(
        'clubs',
        existing_comment='Badminton clubs and organizations',
        schema=None
    )
    op.alter_column('coaches', 'first_name',
               existing_type=sa.VARCHAR(length=100),
               type_=sa.String(length=50),
               existing_nullable=False)
    op.alter_column('coaches', 'last_name',
               existing_type=sa.VARCHAR(length=100),
               type_=sa.String(length=50),
               existing_nullable=False)
    op.alter_column('coaches', 'certification_level',
               existing_type=sa.VARCHAR(length=50),
               comment=None,
               existing_comment='Legacy text field for certification level',
               existing_nullable=True)
    op.alter_column('coaches', 'certification_level_id',
               existing_type=sa.INTEGER(),
               comment=None,
               existing_comment='FK to certification_levels table (recommended)',
               existing_nullable=True)
    op.alter_column('coaches', 'image_url',
               existing_type=sa.TEXT(),
               type_=sa.String(length=255),
               existing_nullable=True)
    op.alter_column('coaches', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
    op.alter_column('coaches', 'updated_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
    op.drop_constraint(op.f('coaches_slug_key'), 'coaches', type_='unique')
    op.drop_index(op.f('idx_coaches_certification_level_id'), table_name='coaches')
    op.drop_index(op.f('idx_coaches_club_id'), table_name='coaches')
    op.drop_index(op.f('idx_coaches_deleted_at'), table_name='coaches')
    op.drop_index(op.f('idx_coaches_slug'), table_name='coaches')
    op.create_index(op.f('ix_coaches_id'), 'coaches', ['id'], unique=False)
    op.create_index(op.f('ix_coaches_slug'), 'coaches', ['slug'], unique=True)
    op.drop_constraint(op.f('coaches_club_id_fkey'), 'coaches', type_='foreignkey')
    op.drop_constraint(op.f('coaches_certification_level_id_fkey'), 'coaches', type_='foreignkey')
    op.drop_table_comment(
        'coaches',
        existing_comment='Badminton coaches and their certifications',
        schema=None
    )
    op.alter_column('individual_matches', 'tie_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('individual_matches', 'match_type',
               existing_type=sa.VARCHAR(length=10),
               type_=sa.String(length=50),
               nullable=True,
               comment=None,
               existing_comment='Type of match: singles (player_1_id vs player_2_id) or doubles (use match_doubles_players table for all 4 players)')
    op.alter_column('individual_matches', 'category',
               existing_type=sa.VARCHAR(length=10),
               type_=sa.String(length=50),
               nullable=True,
               comment=None,
               existing_comment='Match category: MS (Men Singles), WS (Women Singles), MD (Men Doubles), WD (Women Doubles), XD (Mixed Doubles)')
    op.alter_column('individual_matches', 'set_1_score',
               existing_type=sa.VARCHAR(length=10),
               type_=sa.String(length=20),
               existing_nullable=True,
               existing_server_default=sa.text("'[default]'::character varying"))
    op.alter_column('individual_matches', 'set_2_score',
               existing_type=sa.VARCHAR(length=10),
               type_=sa.String(length=20),
               existing_nullable=True,
               existing_server_default=sa.text("'[default]'::character varying"))
    op.alter_column('individual_matches', 'set_3_score',
               existing_type=sa.VARCHAR(length=10),
               type_=sa.String(length=20),
               existing_nullable=True,
               existing_server_default=sa.text("'[default]'::character varying"))
    op.drop_index(op.f('idx_individual_matches_category'), table_name='individual_matches')
    op.drop_index(op.f('idx_individual_matches_created_at'), table_name='individual_matches')
    op.drop_index(op.f('idx_individual_matches_match_type'), table_name='individual_matches')
    op.drop_index(op.f('idx_individual_matches_players'), table_name='individual_matches')
    op.drop_index(op.f('idx_individual_matches_tie_id'), table_name='individual_matches')
    op.drop_index(op.f('idx_individual_matches_umpire_id'), table_name='individual_matches')
    op.drop_index(op.f('idx_individual_matches_winner_id'), table_name='individual_matches')
    op.create_index(op.f('ix_individual_matches_id'), 'individual_matches', ['id'], unique=False)
    op.drop_constraint(op.f('individual_matches_player_2_id_fkey'), 'individual_matches', type_='foreignkey')
    op.drop_constraint(op.f('individual_matches_winner_id_fkey'), 'individual_matches', type_='foreignkey')
    op.drop_constraint(op.f('individual_matches_tie_id_fkey'), 'individual_matches', type_='foreignkey')
    op.drop_constraint(op.f('individual_matches_player_1_id_fkey'), 'individual_matches', type_='foreignkey')
    op.drop_constraint(op.f('individual_matches_umpire_id_fkey'), 'individual_matches', type_='foreignkey')
    op.create_foreign_key(None, 'individual_matches', 'players', ['player_2_id'], ['id'])
    op.create_foreign_key(None, 'individual_matches', 'players', ['winner_id'], ['id'])
    op.create_foreign_key(None, 'individual_matches', 'match_ties', ['tie_id'], ['id'])
    op.create_foreign_key(None, 'individual_matches', 'players', ['player_1_id'], ['id'])
    op.drop_table_comment(
        'individual_matches',
        existing_comment='Individual match results (singles or doubles)',
        schema=None
    )
    op.drop_column('individual_matches', 'updated_at')
    op.drop_column('individual_matches', 'duration_minutes')
    op.drop_column('individual_matches', 'umpire_id')
    op.drop_column('individual_matches', 'created_at')
    op.alter_column('match_rallies', 'server_side',
               existing_type=sa.VARCHAR(length=10),
               nullable=True)
    op.alter_column('match_rallies', 'rally_winner_side',
               existing_type=sa.VARCHAR(length=10),
               nullable=True)
    op.drop_index(op.f('idx_match_rallies_match'), table_name='match_rallies')
    op.drop_index(op.f('idx_match_rallies_server'), table_name='match_rallies')
    op.drop_index(op.f('idx_match_rallies_set'), table_name='match_rallies')
    op.drop_constraint(op.f('match_rallies_individual_match_id_set_number_rally_number_key'), 'match_rallies', type_='unique')
    op.create_index(op.f('ix_match_rallies_id'), 'match_rallies', ['id'], unique=False)
    op.drop_constraint(op.f('match_rallies_individual_match_id_fkey'), 'match_rallies', type_='foreignkey')
    op.drop_constraint(op.f('match_rallies_server_player_id_fkey'), 'match_rallies', type_='foreignkey')
    op.create_foreign_key(None, 'match_rallies', 'individual_matches', ['individual_match_id'], ['id'])
    op.drop_column('match_rallies', 'score_team2')
    op.drop_column('match_rallies', 'created_at')
    op.drop_column('match_rallies', 'score_team1')
    op.drop_column('match_rallies', 'rally_number')
    op.drop_column('match_rallies', 'rally_duration_seconds')
    op.drop_column('match_rallies', 'rally_type')
    op.drop_column('match_rallies', 'rally_strokes')
    op.drop_column('match_rallies', 'server_player_id')
    op.alter_column('match_ties', 'group_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.drop_index(op.f('idx_match_ties_club_1_id'), table_name='match_ties')
    op.drop_index(op.f('idx_match_ties_club_2_id'), table_name='match_ties')
    op.drop_index(op.f('idx_match_ties_clubs'), table_name='match_ties')
    op.drop_index(op.f('idx_match_ties_group_id'), table_name='match_ties')
    op.drop_index(op.f('idx_match_ties_tie_date'), table_name='match_ties')
    op.create_index(op.f('ix_match_ties_id'), 'match_ties', ['id'], unique=False)
    op.drop_constraint(op.f('match_ties_club_1_id_fkey'), 'match_ties', type_='foreignkey')
    op.drop_constraint(op.f('match_ties_club_2_id_fkey'), 'match_ties', type_='foreignkey')
    op.drop_constraint(op.f('match_ties_group_id_fkey'), 'match_ties', type_='foreignkey')
    op.drop_table_comment(
        'match_ties',
        existing_comment='Team matches/ties between two clubs. A tie contains multiple individual matches across different categories.',
        schema=None
    )
    op.drop_column('match_ties', 'updated_at')
    op.drop_column('match_ties', 'stage_label')
    op.drop_column('match_ties', 'created_at')
    op.drop_column('match_ties', 'club_2_id')
    op.drop_column('match_ties', 'tie_date')
    op.drop_column('match_ties', 'overall_score')
    op.drop_column('match_ties', 'club_1_id')
    op.drop_column('match_ties', 'tie_time')
    op.alter_column('players', 'nationality_code',
               existing_type=sa.CHAR(length=3),
               type_=sa.String(length=10),
               existing_nullable=True)
    op.alter_column('players', 'slug',
               existing_type=sa.VARCHAR(length=255),
               type_=sa.String(length=100),
               existing_nullable=False)
    op.alter_column('players', 'image_url',
               existing_type=sa.TEXT(),
               type_=sa.String(length=255),
               existing_nullable=True)
    op.drop_index(op.f('idx_players_club_id'), table_name='players')
    op.drop_index(op.f('idx_players_deleted_at'), table_name='players')
    op.drop_index(op.f('idx_players_gender'), table_name='players')
    op.drop_index(op.f('idx_players_slug'), table_name='players')
    op.drop_constraint(op.f('players_slug_key'), 'players', type_='unique')
    op.create_index(op.f('ix_players_club_id'), 'players', ['club_id'], unique=False)
    op.create_index(op.f('ix_players_id'), 'players', ['id'], unique=False)
    op.create_index(op.f('ix_players_slug'), 'players', ['slug'], unique=True)
    op.drop_constraint(op.f('players_club_id_fkey'), 'players', type_='foreignkey')
    op.drop_constraint(op.f('players_nationality_code_fkey'), 'players', type_='foreignkey')
    op.create_foreign_key(None, 'players', 'clubs', ['club_id'], ['id'])
    op.drop_table_comment(
        'players',
        existing_comment='Badminton players and their information',
        schema=None
    )
    op.drop_column('players', 'global_rank')
    op.drop_column('players', 'last_name_geo')
    op.drop_column('players', 'first_name_geo')
    op.alter_column('tournament_courts', 'court_number',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.drop_index(op.f('tournament_courts_tournament_id_idx'), table_name='tournament_courts')
    op.create_index(op.f('ix_tournament_courts_id'), 'tournament_courts', ['id'], unique=False)
    op.drop_constraint(op.f('tournament_courts_tournament_id_fkey'), 'tournament_courts', type_='foreignkey')
    op.create_foreign_key(None, 'tournament_courts', 'tournaments', ['tournament_id'], ['id'])
    op.drop_column('tournament_courts', 'created_at')
    op.alter_column('tournament_entries', 'entry_name',
               existing_type=sa.VARCHAR(length=150),
               type_=sa.String(length=255),
               existing_nullable=False)
    op.alter_column('tournament_entries', 'entry_type',
               existing_type=sa.VARCHAR(length=20),
               type_=sa.String(length=50),
               nullable=True)
    op.alter_column('tournament_entries', 'entry_category',
               existing_type=sa.VARCHAR(length=10),
               type_=sa.String(length=50),
               existing_nullable=True)
    op.alter_column('tournament_entries', 'entry_discipline',
               existing_type=sa.VARCHAR(length=20),
               type_=sa.String(length=50),
               existing_nullable=True)
    op.alter_column('tournament_entries', 'approval_status',
               existing_type=sa.VARCHAR(length=20),
               type_=sa.String(length=50),
               nullable=True,
               existing_server_default=sa.text("'pending'::character varying"))
    op.drop_index(op.f('tournament_entries_tournament_id_idx'), table_name='tournament_entries')
    op.create_index(op.f('ix_tournament_entries_id'), 'tournament_entries', ['id'], unique=False)
    op.drop_constraint(op.f('tournament_entries_event_id_fkey'), 'tournament_entries', type_='foreignkey')
    op.drop_constraint(op.f('tournament_entries_tournament_id_fkey'), 'tournament_entries', type_='foreignkey')
    op.create_foreign_key(None, 'tournament_entries', 'tournaments', ['tournament_id'], ['id'])
    op.drop_column('tournament_entries', 'updated_at')
    op.drop_column('tournament_entries', 'created_at')
    op.alter_column('tournament_events', 'event_name',
               existing_type=sa.VARCHAR(length=150),
               type_=sa.String(length=100),
               nullable=True)
    op.alter_column('tournament_events', 'discipline',
               existing_type=sa.VARCHAR(length=20),
               type_=sa.String(length=50),
               nullable=True)
    op.alter_column('tournament_events', 'category',
               existing_type=sa.VARCHAR(length=10),
               type_=sa.String(length=50),
               nullable=True)
    op.alter_column('tournament_events', 'level',
               existing_type=sa.VARCHAR(length=20),
               type_=sa.String(length=50),
               nullable=True)
    op.alter_column('tournament_events', 'scoring_format',
               existing_type=sa.VARCHAR(length=20),
               type_=sa.String(length=50),
               nullable=True)
    op.alter_column('tournament_events', 'max_entries',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('tournament_events', 'entry_fee',
               existing_type=sa.NUMERIC(precision=10, scale=2),
               type_=sa.Integer(),
               existing_nullable=True)
    op.alter_column('tournament_events', 'member_perks',
               existing_type=sa.TEXT(),
               type_=sa.String(length=255),
               existing_nullable=True)
    op.alter_column('tournament_events', 'draw_type',
               existing_type=sa.VARCHAR(length=30),
               type_=sa.String(length=50),
               existing_nullable=True)
    op.alter_column('tournament_events', 'draw_setup',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               type_=sa.String(length=255),
               existing_nullable=True)
    op.alter_column('tournament_events', 'generation_rules',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               type_=sa.String(length=255),
               existing_nullable=True)
    op.alter_column('tournament_events', 'seeding_mode',
               existing_type=sa.VARCHAR(length=30),
               type_=sa.String(length=50),
               existing_nullable=True)
    op.alter_column('tournament_events', 'lock_entries',
               existing_type=sa.BOOLEAN(),
               nullable=True,
               existing_server_default=sa.text('false'))
    op.alter_column('tournament_events', 'publish_bracket_preview',
               existing_type=sa.BOOLEAN(),
               nullable=True,
               existing_server_default=sa.text('false'))
    op.alter_column('tournament_events', 'bracket_visibility',
               existing_type=sa.VARCHAR(length=20),
               type_=sa.String(length=50),
               existing_nullable=True,
               existing_server_default=sa.text("'public'::character varying"))
    op.drop_index(op.f('tournament_events_tournament_id_idx'), table_name='tournament_events')
    op.create_index(op.f('ix_tournament_events_id'), 'tournament_events', ['id'], unique=False)
    op.drop_constraint(op.f('tournament_events_tournament_id_fkey'), 'tournament_events', type_='foreignkey')
    op.create_foreign_key(None, 'tournament_events', 'tournaments', ['tournament_id'], ['id'])
    op.drop_column('tournament_events', 'updated_at')
    op.drop_column('tournament_events', 'created_at')
    op.alter_column('tournament_time_blocks', 'block_type',
               existing_type=sa.VARCHAR(length=20),
               type_=sa.String(length=50),
               nullable=True)
    op.alter_column('tournament_time_blocks', 'block_label',
               existing_type=sa.VARCHAR(length=20),
               type_=sa.String(length=100),
               existing_nullable=True)
    op.alter_column('tournament_time_blocks', 'start_time',
               existing_type=postgresql.TIME(),
               type_=sa.String(length=10),
               existing_nullable=False)
    op.alter_column('tournament_time_blocks', 'end_time',
               existing_type=postgresql.TIME(),
               type_=sa.String(length=10),
               existing_nullable=False)
    op.alter_column('tournament_time_blocks', 'lunch_break_enabled',
               existing_type=sa.BOOLEAN(),
               nullable=True,
               existing_server_default=sa.text('false'))
    op.alter_column('tournament_time_blocks', 'break_start_time',
               existing_type=postgresql.TIME(),
               type_=sa.String(length=10),
               existing_nullable=True)
    op.alter_column('tournament_time_blocks', 'break_end_time',
               existing_type=postgresql.TIME(),
               type_=sa.String(length=10),
               existing_nullable=True)
    op.drop_index(op.f('tournament_time_blocks_tournament_id_idx'), table_name='tournament_time_blocks')
    op.create_index(op.f('ix_tournament_time_blocks_id'), 'tournament_time_blocks', ['id'], unique=False)
    op.drop_constraint(op.f('tournament_time_blocks_tournament_id_fkey'), 'tournament_time_blocks', type_='foreignkey')
    op.create_foreign_key(None, 'tournament_time_blocks', 'tournaments', ['tournament_id'], ['id'])
    op.alter_column('tournament_venues', 'venue_name',
               existing_type=sa.VARCHAR(length=150),
               type_=sa.String(length=255),
               existing_nullable=True)
    op.alter_column('tournament_venues', 'venue_country_code',
               existing_type=sa.CHAR(length=3),
               type_=sa.String(length=10),
               existing_nullable=True)
    op.create_unique_constraint(None, 'tournament_venues', ['tournament_id'])
    op.drop_constraint(op.f('tournament_venues_tournament_id_fkey'), 'tournament_venues', type_='foreignkey')
    op.create_foreign_key(None, 'tournament_venues', 'tournaments', ['tournament_id'], ['id'])
    op.drop_column('tournament_venues', 'updated_at')
    op.drop_column('tournament_venues', 'created_at')
    op.add_column('tournament_winners', sa.Column('id', sa.Integer(), nullable=True))
    op.execute("CREATE SEQUENCE IF NOT EXISTS tournament_winners_id_seq")
    op.execute("UPDATE tournament_winners SET id = nextval('tournament_winners_id_seq')")
    op.alter_column('tournament_winners', 'id', nullable=False)
    op.execute("ALTER TABLE tournament_winners ALTER COLUMN id SET DEFAULT nextval('tournament_winners_id_seq')")
    op.execute("ALTER SEQUENCE tournament_winners_id_seq OWNED BY tournament_winners.id")
    op.drop_index(op.f('idx_tournament_winners_first_place'), table_name='tournament_winners')
    op.drop_index(op.f('idx_tournament_winners_second_place'), table_name='tournament_winners')
    op.drop_index(op.f('idx_tournament_winners_third_place'), table_name='tournament_winners')
    op.create_index(op.f('ix_tournament_winners_id'), 'tournament_winners', ['id'], unique=False)
    op.create_unique_constraint(None, 'tournament_winners', ['tournament_id'])
    op.drop_constraint(op.f('tournament_winners_first_place_player_id_fkey'), 'tournament_winners', type_='foreignkey')
    op.drop_constraint(op.f('tournament_winners_tournament_id_fkey'), 'tournament_winners', type_='foreignkey')
    op.drop_constraint(op.f('tournament_winners_third_place_club_id_fkey'), 'tournament_winners', type_='foreignkey')
    op.drop_constraint(op.f('tournament_winners_second_place_player_id_fkey'), 'tournament_winners', type_='foreignkey')
    op.drop_constraint(op.f('tournament_winners_first_place_club_id_fkey'), 'tournament_winners', type_='foreignkey')
    op.drop_constraint(op.f('tournament_winners_third_place_player_id_fkey'), 'tournament_winners', type_='foreignkey')
    op.drop_constraint(op.f('tournament_winners_second_place_club_id_fkey'), 'tournament_winners', type_='foreignkey')
    op.create_foreign_key(None, 'tournament_winners', 'tournaments', ['tournament_id'], ['id'])
    op.drop_column('tournament_winners', 'updated_at')
    op.drop_column('tournament_winners', 'created_at')
    op.alter_column('tournaments', 'organizer_organization_id',
               existing_type=sa.BIGINT(),
               type_=sa.Integer(),
               nullable=False)
    op.alter_column('tournaments', 'status',
               existing_type=sa.VARCHAR(length=50),
               nullable=False,
               comment=None,
               existing_comment='Tournament status: Upcoming, In Progress, Finished, or Cancelled',
               existing_server_default=sa.text("'DRAFT'::character varying"))
    op.alter_column('tournaments', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
    op.alter_column('tournaments', 'updated_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
    op.drop_index(op.f('idx_tournaments_deleted_at'), table_name='tournaments')
    op.drop_index(op.f('idx_tournaments_slug'), table_name='tournaments')
    op.drop_index(op.f('idx_tournaments_status'), table_name='tournaments')
    op.drop_index(op.f('idx_tournaments_status_current_phase'), table_name='tournaments')
    op.drop_index(op.f('idx_tournaments_status_updated_at'), table_name='tournaments')
    op.drop_constraint(op.f('tournaments_slug_key'), 'tournaments', type_='unique')
    op.drop_index(op.f('tournaments_slug_uq'), table_name='tournaments')
    op.create_index(op.f('ix_tournaments_id'), 'tournaments', ['id'], unique=False)
    op.create_index(op.f('ix_tournaments_organizer_organization_id'), 'tournaments', ['organizer_organization_id'], unique=False)
    op.create_index(op.f('ix_tournaments_slug'), 'tournaments', ['slug'], unique=True)
    op.drop_constraint(op.f('tournaments_organizer_org_fk'), 'tournaments', type_='foreignkey')
    op.drop_table_comment(
        'tournaments',
        existing_comment='Tournament events and competitions',
        schema=None
    )
    op.alter_column('users', 'email',
               existing_type=sa.TEXT(),
               type_=sa.String(length=255),
               existing_nullable=False)
    op.alter_column('users', 'password_hash',
               existing_type=sa.TEXT(),
               type_=sa.String(length=255),
               existing_nullable=False)
    op.alter_column('users', 'role',
               existing_type=sa.VARCHAR(length=50),
               nullable=False,
               existing_server_default=sa.text("'viewer'::character varying"))
    op.drop_constraint(op.f('users_email_key'), 'users', type_='unique')
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_index(op.f('ix_users_id'), 'users', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_users_id'), table_name='users')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.create_unique_constraint(op.f('users_email_key'), 'users', ['email'], postgresql_nulls_not_distinct=False)
    op.alter_column('users', 'role',
               existing_type=sa.VARCHAR(length=50),
               nullable=True,
               existing_server_default=sa.text("'viewer'::character varying"))
    op.alter_column('users', 'password_hash',
               existing_type=sa.String(length=255),
               type_=sa.TEXT(),
               existing_nullable=False)
    op.alter_column('users', 'email',
               existing_type=sa.String(length=255),
               type_=sa.TEXT(),
               existing_nullable=False)
    op.create_table_comment(
        'tournaments',
        'Tournament events and competitions',
        existing_comment=None,
        schema=None
    )
    op.create_foreign_key(op.f('tournaments_organizer_org_fk'), 'tournaments', 'organizations', ['organizer_organization_id'], ['id'])
    op.drop_index(op.f('ix_tournaments_slug'), table_name='tournaments')
    op.drop_index(op.f('ix_tournaments_organizer_organization_id'), table_name='tournaments')
    op.drop_index(op.f('ix_tournaments_id'), table_name='tournaments')
    op.create_index(op.f('tournaments_slug_uq'), 'tournaments', ['slug'], unique=True)
    op.create_unique_constraint(op.f('tournaments_slug_key'), 'tournaments', ['slug'], postgresql_nulls_not_distinct=False)
    op.create_index(op.f('idx_tournaments_status_updated_at'), 'tournaments', ['status', sa.literal_column('updated_at DESC')], unique=False)
    op.create_index(op.f('idx_tournaments_status_current_phase'), 'tournaments', ['status', 'current_phase'], unique=False)
    op.create_index(op.f('idx_tournaments_status'), 'tournaments', ['status'], unique=False)
    op.create_index(op.f('idx_tournaments_slug'), 'tournaments', ['slug'], unique=False)
    op.create_index(op.f('idx_tournaments_deleted_at'), 'tournaments', ['deleted_at'], unique=False)
    op.alter_column('tournaments', 'updated_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
    op.alter_column('tournaments', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
    op.alter_column('tournaments', 'status',
               existing_type=sa.VARCHAR(length=50),
               nullable=True,
               comment='Tournament status: Upcoming, In Progress, Finished, or Cancelled',
               existing_server_default=sa.text("'DRAFT'::character varying"))
    op.alter_column('tournaments', 'organizer_organization_id',
               existing_type=sa.Integer(),
               type_=sa.BIGINT(),
               nullable=True)
    op.add_column('tournament_winners', sa.Column('created_at', postgresql.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'), autoincrement=False, nullable=True))
    op.add_column('tournament_winners', sa.Column('updated_at', postgresql.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'tournament_winners', type_='foreignkey')
    op.create_foreign_key(op.f('tournament_winners_second_place_club_id_fkey'), 'tournament_winners', 'clubs', ['second_place_club_id'], ['id'], ondelete='SET NULL')
    op.create_foreign_key(op.f('tournament_winners_third_place_player_id_fkey'), 'tournament_winners', 'players', ['third_place_player_id'], ['id'], ondelete='SET NULL')
    op.create_foreign_key(op.f('tournament_winners_first_place_club_id_fkey'), 'tournament_winners', 'clubs', ['first_place_club_id'], ['id'], ondelete='SET NULL')
    op.create_foreign_key(op.f('tournament_winners_second_place_player_id_fkey'), 'tournament_winners', 'players', ['second_place_player_id'], ['id'], ondelete='SET NULL')
    op.create_foreign_key(op.f('tournament_winners_third_place_club_id_fkey'), 'tournament_winners', 'clubs', ['third_place_club_id'], ['id'], ondelete='SET NULL')
    op.create_foreign_key(op.f('tournament_winners_tournament_id_fkey'), 'tournament_winners', 'tournaments', ['tournament_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(op.f('tournament_winners_first_place_player_id_fkey'), 'tournament_winners', 'players', ['first_place_player_id'], ['id'], ondelete='SET NULL')
    op.drop_constraint(None, 'tournament_winners', type_='unique')
    op.drop_index(op.f('ix_tournament_winners_id'), table_name='tournament_winners')
    op.create_index(op.f('idx_tournament_winners_third_place'), 'tournament_winners', ['third_place_player_id'], unique=False)
    op.create_index(op.f('idx_tournament_winners_second_place'), 'tournament_winners', ['second_place_player_id'], unique=False)
    op.create_index(op.f('idx_tournament_winners_first_place'), 'tournament_winners', ['first_place_player_id'], unique=False)
    op.drop_column('tournament_winners', 'id')
    op.add_column('tournament_venues', sa.Column('created_at', postgresql.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'), autoincrement=False, nullable=True))
    op.add_column('tournament_venues', sa.Column('updated_at', postgresql.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'tournament_venues', type_='foreignkey')
    op.create_foreign_key(op.f('tournament_venues_tournament_id_fkey'), 'tournament_venues', 'tournaments', ['tournament_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint(None, 'tournament_venues', type_='unique')
    op.alter_column('tournament_venues', 'venue_country_code',
               existing_type=sa.String(length=10),
               type_=sa.CHAR(length=3),
               existing_nullable=True)
    op.alter_column('tournament_venues', 'venue_name',
               existing_type=sa.String(length=255),
               type_=sa.VARCHAR(length=150),
               existing_nullable=True)
    op.drop_constraint(None, 'tournament_time_blocks', type_='foreignkey')
    op.create_foreign_key(op.f('tournament_time_blocks_tournament_id_fkey'), 'tournament_time_blocks', 'tournaments', ['tournament_id'], ['id'], ondelete='CASCADE')
    op.drop_index(op.f('ix_tournament_time_blocks_id'), table_name='tournament_time_blocks')
    op.create_index(op.f('tournament_time_blocks_tournament_id_idx'), 'tournament_time_blocks', ['tournament_id'], unique=False)
    op.alter_column('tournament_time_blocks', 'break_end_time',
               existing_type=sa.String(length=10),
               type_=postgresql.TIME(),
               existing_nullable=True)
    op.alter_column('tournament_time_blocks', 'break_start_time',
               existing_type=sa.String(length=10),
               type_=postgresql.TIME(),
               existing_nullable=True)
    op.alter_column('tournament_time_blocks', 'lunch_break_enabled',
               existing_type=sa.BOOLEAN(),
               nullable=False,
               existing_server_default=sa.text('false'))
    op.alter_column('tournament_time_blocks', 'end_time',
               existing_type=sa.String(length=10),
               type_=postgresql.TIME(),
               existing_nullable=False)
    op.alter_column('tournament_time_blocks', 'start_time',
               existing_type=sa.String(length=10),
               type_=postgresql.TIME(),
               existing_nullable=False)
    op.alter_column('tournament_time_blocks', 'block_label',
               existing_type=sa.String(length=100),
               type_=sa.VARCHAR(length=20),
               existing_nullable=True)
    op.alter_column('tournament_time_blocks', 'block_type',
               existing_type=sa.String(length=50),
               type_=sa.VARCHAR(length=20),
               nullable=False)
    op.add_column('tournament_events', sa.Column('created_at', postgresql.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'), autoincrement=False, nullable=True))
    op.add_column('tournament_events', sa.Column('updated_at', postgresql.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'tournament_events', type_='foreignkey')
    op.create_foreign_key(op.f('tournament_events_tournament_id_fkey'), 'tournament_events', 'tournaments', ['tournament_id'], ['id'], ondelete='CASCADE')
    op.drop_index(op.f('ix_tournament_events_id'), table_name='tournament_events')
    op.create_index(op.f('tournament_events_tournament_id_idx'), 'tournament_events', ['tournament_id'], unique=False)
    op.alter_column('tournament_events', 'bracket_visibility',
               existing_type=sa.String(length=50),
               type_=sa.VARCHAR(length=20),
               existing_nullable=True,
               existing_server_default=sa.text("'public'::character varying"))
    op.alter_column('tournament_events', 'publish_bracket_preview',
               existing_type=sa.BOOLEAN(),
               nullable=False,
               existing_server_default=sa.text('false'))
    op.alter_column('tournament_events', 'lock_entries',
               existing_type=sa.BOOLEAN(),
               nullable=False,
               existing_server_default=sa.text('false'))
    op.alter_column('tournament_events', 'seeding_mode',
               existing_type=sa.String(length=50),
               type_=sa.VARCHAR(length=30),
               existing_nullable=True)
    op.alter_column('tournament_events', 'generation_rules',
               existing_type=sa.String(length=255),
               type_=postgresql.JSONB(astext_type=sa.Text()),
               existing_nullable=True)
    op.alter_column('tournament_events', 'draw_setup',
               existing_type=sa.String(length=255),
               type_=postgresql.JSONB(astext_type=sa.Text()),
               existing_nullable=True)
    op.alter_column('tournament_events', 'draw_type',
               existing_type=sa.String(length=50),
               type_=sa.VARCHAR(length=30),
               existing_nullable=True)
    op.alter_column('tournament_events', 'member_perks',
               existing_type=sa.String(length=255),
               type_=sa.TEXT(),
               existing_nullable=True)
    op.alter_column('tournament_events', 'entry_fee',
               existing_type=sa.Integer(),
               type_=sa.NUMERIC(precision=10, scale=2),
               existing_nullable=True)
    op.alter_column('tournament_events', 'max_entries',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('tournament_events', 'scoring_format',
               existing_type=sa.String(length=50),
               type_=sa.VARCHAR(length=20),
               nullable=False)
    op.alter_column('tournament_events', 'level',
               existing_type=sa.String(length=50),
               type_=sa.VARCHAR(length=20),
               nullable=False)
    op.alter_column('tournament_events', 'category',
               existing_type=sa.String(length=50),
               type_=sa.VARCHAR(length=10),
               nullable=False)
    op.alter_column('tournament_events', 'discipline',
               existing_type=sa.String(length=50),
               type_=sa.VARCHAR(length=20),
               nullable=False)
    op.alter_column('tournament_events', 'event_name',
               existing_type=sa.String(length=100),
               type_=sa.VARCHAR(length=150),
               nullable=False)
    op.add_column('tournament_entries', sa.Column('created_at', postgresql.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'), autoincrement=False, nullable=True))
    op.add_column('tournament_entries', sa.Column('updated_at', postgresql.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'tournament_entries', type_='foreignkey')
    op.create_foreign_key(op.f('tournament_entries_tournament_id_fkey'), 'tournament_entries', 'tournaments', ['tournament_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(op.f('tournament_entries_event_id_fkey'), 'tournament_entries', 'tournament_events', ['event_id'], ['id'], ondelete='SET NULL')
    op.drop_index(op.f('ix_tournament_entries_id'), table_name='tournament_entries')
    op.create_index(op.f('tournament_entries_tournament_id_idx'), 'tournament_entries', ['tournament_id'], unique=False)
    op.alter_column('tournament_entries', 'approval_status',
               existing_type=sa.String(length=50),
               type_=sa.VARCHAR(length=20),
               nullable=False,
               existing_server_default=sa.text("'pending'::character varying"))
    op.alter_column('tournament_entries', 'entry_discipline',
               existing_type=sa.String(length=50),
               type_=sa.VARCHAR(length=20),
               existing_nullable=True)
    op.alter_column('tournament_entries', 'entry_category',
               existing_type=sa.String(length=50),
               type_=sa.VARCHAR(length=10),
               existing_nullable=True)
    op.alter_column('tournament_entries', 'entry_type',
               existing_type=sa.String(length=50),
               type_=sa.VARCHAR(length=20),
               nullable=False)
    op.alter_column('tournament_entries', 'entry_name',
               existing_type=sa.String(length=255),
               type_=sa.VARCHAR(length=150),
               existing_nullable=False)
    op.add_column('tournament_courts', sa.Column('created_at', postgresql.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'tournament_courts', type_='foreignkey')
    op.create_foreign_key(op.f('tournament_courts_tournament_id_fkey'), 'tournament_courts', 'tournaments', ['tournament_id'], ['id'], ondelete='CASCADE')
    op.drop_index(op.f('ix_tournament_courts_id'), table_name='tournament_courts')
    op.create_index(op.f('tournament_courts_tournament_id_idx'), 'tournament_courts', ['tournament_id'], unique=False)
    op.alter_column('tournament_courts', 'court_number',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.add_column('players', sa.Column('first_name_geo', sa.VARCHAR(length=100), autoincrement=False, nullable=True))
    op.add_column('players', sa.Column('last_name_geo', sa.VARCHAR(length=100), autoincrement=False, nullable=True))
    op.add_column('players', sa.Column('global_rank', sa.INTEGER(), server_default=sa.text('0'), autoincrement=False, nullable=True, comment='Global badminton ranking (0 means unranked)'))
    op.create_table_comment(
        'players',
        'Badminton players and their information',
        existing_comment=None,
        schema=None
    )
    op.drop_constraint(None, 'players', type_='foreignkey')
    op.create_foreign_key(op.f('players_nationality_code_fkey'), 'players', 'countries', ['nationality_code'], ['code'], ondelete='SET NULL')
    op.create_foreign_key(op.f('players_club_id_fkey'), 'players', 'clubs', ['club_id'], ['id'], ondelete='SET NULL')
    op.drop_index(op.f('ix_players_slug'), table_name='players')
    op.drop_index(op.f('ix_players_id'), table_name='players')
    op.drop_index(op.f('ix_players_club_id'), table_name='players')
    op.create_unique_constraint(op.f('players_slug_key'), 'players', ['slug'], postgresql_nulls_not_distinct=False)
    op.create_index(op.f('idx_players_slug'), 'players', ['slug'], unique=False)
    op.create_index(op.f('idx_players_gender'), 'players', ['gender'], unique=False)
    op.create_index(op.f('idx_players_deleted_at'), 'players', ['deleted_at'], unique=False)
    op.create_index(op.f('idx_players_club_id'), 'players', ['club_id'], unique=False)
    op.alter_column('players', 'image_url',
               existing_type=sa.String(length=255),
               type_=sa.TEXT(),
               existing_nullable=True)
    op.alter_column('players', 'slug',
               existing_type=sa.String(length=100),
               type_=sa.VARCHAR(length=255),
               existing_nullable=False)
    op.alter_column('players', 'nationality_code',
               existing_type=sa.String(length=10),
               type_=sa.CHAR(length=3),
               existing_nullable=True)
    op.add_column('match_ties', sa.Column('tie_time', postgresql.TIME(), autoincrement=False, nullable=True))
    op.add_column('match_ties', sa.Column('club_1_id', sa.INTEGER(), autoincrement=False, nullable=False))
    op.add_column('match_ties', sa.Column('overall_score', sa.VARCHAR(length=20), autoincrement=False, nullable=True))
    op.add_column('match_ties', sa.Column('tie_date', sa.DATE(), autoincrement=False, nullable=True))
    op.add_column('match_ties', sa.Column('club_2_id', sa.INTEGER(), autoincrement=False, nullable=False))
    op.add_column('match_ties', sa.Column('created_at', postgresql.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'), autoincrement=False, nullable=True))
    op.add_column('match_ties', sa.Column('stage_label', sa.VARCHAR(length=50), autoincrement=False, nullable=True))
    op.add_column('match_ties', sa.Column('updated_at', postgresql.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'), autoincrement=False, nullable=True))
    op.create_table_comment(
        'match_ties',
        'Team matches/ties between two clubs. A tie contains multiple individual matches across different categories.',
        existing_comment=None,
        schema=None
    )
    op.create_foreign_key(op.f('match_ties_group_id_fkey'), 'match_ties', 'tournament_groups', ['group_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(op.f('match_ties_club_2_id_fkey'), 'match_ties', 'clubs', ['club_2_id'], ['id'], ondelete='RESTRICT')
    op.create_foreign_key(op.f('match_ties_club_1_id_fkey'), 'match_ties', 'clubs', ['club_1_id'], ['id'], ondelete='RESTRICT')
    op.drop_index(op.f('ix_match_ties_id'), table_name='match_ties')
    op.create_index(op.f('idx_match_ties_tie_date'), 'match_ties', ['tie_date'], unique=False)
    op.create_index(op.f('idx_match_ties_group_id'), 'match_ties', ['group_id'], unique=False)
    op.create_index(op.f('idx_match_ties_clubs'), 'match_ties', ['club_1_id', 'club_2_id'], unique=False)
    op.create_index(op.f('idx_match_ties_club_2_id'), 'match_ties', ['club_2_id'], unique=False)
    op.create_index(op.f('idx_match_ties_club_1_id'), 'match_ties', ['club_1_id'], unique=False)
    op.alter_column('match_ties', 'group_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.add_column('match_rallies', sa.Column('server_player_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('match_rallies', sa.Column('rally_strokes', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('match_rallies', sa.Column('rally_type', sa.VARCHAR(length=50), autoincrement=False, nullable=True))
    op.add_column('match_rallies', sa.Column('rally_duration_seconds', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('match_rallies', sa.Column('rally_number', sa.INTEGER(), autoincrement=False, nullable=False))
    op.add_column('match_rallies', sa.Column('score_team1', sa.INTEGER(), autoincrement=False, nullable=False))
    op.add_column('match_rallies', sa.Column('created_at', postgresql.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'), autoincrement=False, nullable=True))
    op.add_column('match_rallies', sa.Column('score_team2', sa.INTEGER(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'match_rallies', type_='foreignkey')
    op.create_foreign_key(op.f('match_rallies_server_player_id_fkey'), 'match_rallies', 'players', ['server_player_id'], ['id'])
    op.create_foreign_key(op.f('match_rallies_individual_match_id_fkey'), 'match_rallies', 'individual_matches', ['individual_match_id'], ['id'], ondelete='CASCADE')
    op.drop_index(op.f('ix_match_rallies_id'), table_name='match_rallies')
    op.create_unique_constraint(op.f('match_rallies_individual_match_id_set_number_rally_number_key'), 'match_rallies', ['individual_match_id', 'set_number', 'rally_number'], postgresql_nulls_not_distinct=False)
    op.create_index(op.f('idx_match_rallies_set'), 'match_rallies', ['set_number'], unique=False)
    op.create_index(op.f('idx_match_rallies_server'), 'match_rallies', ['server_side'], unique=False)
    op.create_index(op.f('idx_match_rallies_match'), 'match_rallies', ['individual_match_id'], unique=False)
    op.alter_column('match_rallies', 'rally_winner_side',
               existing_type=sa.VARCHAR(length=10),
               nullable=False)
    op.alter_column('match_rallies', 'server_side',
               existing_type=sa.VARCHAR(length=10),
               nullable=False)
    op.add_column('individual_matches', sa.Column('created_at', postgresql.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'), autoincrement=False, nullable=True))
    op.add_column('individual_matches', sa.Column('umpire_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('individual_matches', sa.Column('duration_minutes', sa.INTEGER(), autoincrement=False, nullable=True, comment='Match duration in minutes (1-300)'))
    op.add_column('individual_matches', sa.Column('updated_at', postgresql.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'), autoincrement=False, nullable=True))
    op.create_table_comment(
        'individual_matches',
        'Individual match results (singles or doubles)',
        existing_comment=None,
        schema=None
    )
    op.drop_constraint(None, 'individual_matches', type_='foreignkey')
    op.drop_constraint(None, 'individual_matches', type_='foreignkey')
    op.drop_constraint(None, 'individual_matches', type_='foreignkey')
    op.drop_constraint(None, 'individual_matches', type_='foreignkey')
    op.create_foreign_key(op.f('individual_matches_umpire_id_fkey'), 'individual_matches', 'umpires', ['umpire_id'], ['id'], ondelete='SET NULL')
    op.create_foreign_key(op.f('individual_matches_player_1_id_fkey'), 'individual_matches', 'players', ['player_1_id'], ['id'], ondelete='SET NULL')
    op.create_foreign_key(op.f('individual_matches_tie_id_fkey'), 'individual_matches', 'match_ties', ['tie_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(op.f('individual_matches_winner_id_fkey'), 'individual_matches', 'players', ['winner_id'], ['id'], ondelete='SET NULL')
    op.create_foreign_key(op.f('individual_matches_player_2_id_fkey'), 'individual_matches', 'players', ['player_2_id'], ['id'], ondelete='SET NULL')
    op.drop_index(op.f('ix_individual_matches_id'), table_name='individual_matches')
    op.create_index(op.f('idx_individual_matches_winner_id'), 'individual_matches', ['winner_id'], unique=False)
    op.create_index(op.f('idx_individual_matches_umpire_id'), 'individual_matches', ['umpire_id'], unique=False)
    op.create_index(op.f('idx_individual_matches_tie_id'), 'individual_matches', ['tie_id'], unique=False)
    op.create_index(op.f('idx_individual_matches_players'), 'individual_matches', ['player_1_id', 'player_2_id'], unique=False)
    op.create_index(op.f('idx_individual_matches_match_type'), 'individual_matches', ['match_type'], unique=False)
    op.create_index(op.f('idx_individual_matches_created_at'), 'individual_matches', ['created_at'], unique=False)
    op.create_index(op.f('idx_individual_matches_category'), 'individual_matches', ['category'], unique=False)
    op.alter_column('individual_matches', 'set_3_score',
               existing_type=sa.String(length=20),
               type_=sa.VARCHAR(length=10),
               existing_nullable=True,
               existing_server_default=sa.text("'[default]'::character varying"))
    op.alter_column('individual_matches', 'set_2_score',
               existing_type=sa.String(length=20),
               type_=sa.VARCHAR(length=10),
               existing_nullable=True,
               existing_server_default=sa.text("'[default]'::character varying"))
    op.alter_column('individual_matches', 'set_1_score',
               existing_type=sa.String(length=20),
               type_=sa.VARCHAR(length=10),
               existing_nullable=True,
               existing_server_default=sa.text("'[default]'::character varying"))
    op.alter_column('individual_matches', 'category',
               existing_type=sa.String(length=50),
               type_=sa.VARCHAR(length=10),
               nullable=False,
               comment='Match category: MS (Men Singles), WS (Women Singles), MD (Men Doubles), WD (Women Doubles), XD (Mixed Doubles)')
    op.alter_column('individual_matches', 'match_type',
               existing_type=sa.String(length=50),
               type_=sa.VARCHAR(length=10),
               nullable=False,
               comment='Type of match: singles (player_1_id vs player_2_id) or doubles (use match_doubles_players table for all 4 players)')
    op.alter_column('individual_matches', 'tie_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.create_table_comment(
        'coaches',
        'Badminton coaches and their certifications',
        existing_comment=None,
        schema=None
    )
    op.create_foreign_key(op.f('coaches_certification_level_id_fkey'), 'coaches', 'certification_levels', ['certification_level_id'], ['id'], ondelete='SET NULL')
    op.create_foreign_key(op.f('coaches_club_id_fkey'), 'coaches', 'clubs', ['club_id'], ['id'], ondelete='SET NULL')
    op.drop_index(op.f('ix_coaches_slug'), table_name='coaches')
    op.drop_index(op.f('ix_coaches_id'), table_name='coaches')
    op.create_index(op.f('idx_coaches_slug'), 'coaches', ['slug'], unique=False)
    op.create_index(op.f('idx_coaches_deleted_at'), 'coaches', ['deleted_at'], unique=False)
    op.create_index(op.f('idx_coaches_club_id'), 'coaches', ['club_id'], unique=False)
    op.create_index(op.f('idx_coaches_certification_level_id'), 'coaches', ['certification_level_id'], unique=False)
    op.create_unique_constraint(op.f('coaches_slug_key'), 'coaches', ['slug'], postgresql_nulls_not_distinct=False)
    op.alter_column('coaches', 'updated_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
    op.alter_column('coaches', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
    op.alter_column('coaches', 'image_url',
               existing_type=sa.String(length=255),
               type_=sa.TEXT(),
               existing_nullable=True)
    op.alter_column('coaches', 'certification_level_id',
               existing_type=sa.INTEGER(),
               comment='FK to certification_levels table (recommended)',
               existing_nullable=True)
    op.alter_column('coaches', 'certification_level',
               existing_type=sa.VARCHAR(length=50),
               comment='Legacy text field for certification level',
               existing_nullable=True)
    op.alter_column('coaches', 'last_name',
               existing_type=sa.String(length=50),
               type_=sa.VARCHAR(length=100),
               existing_nullable=False)
    op.alter_column('coaches', 'first_name',
               existing_type=sa.String(length=50),
               type_=sa.VARCHAR(length=100),
               existing_nullable=False)
    op.create_table_comment(
        'clubs',
        'Badminton clubs and organizations',
        existing_comment=None,
        schema=None
    )
    op.create_foreign_key(op.f('fk_clubs_head_coach'), 'clubs', 'coaches', ['head_coach_id'], ['id'], ondelete='SET NULL')
    op.drop_index(op.f('ix_clubs_slug'), table_name='clubs')
    op.drop_index(op.f('ix_clubs_id'), table_name='clubs')
    op.create_index(op.f('idx_clubs_slug'), 'clubs', ['slug'], unique=False)
    op.create_index(op.f('idx_clubs_head_coach_id'), 'clubs', ['head_coach_id'], unique=False)
    op.create_index(op.f('idx_clubs_deleted_at'), 'clubs', ['deleted_at'], unique=False)
    op.create_unique_constraint(op.f('clubs_slug_key'), 'clubs', ['slug'], postgresql_nulls_not_distinct=False)
    op.alter_column('clubs', 'updated_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
    op.alter_column('clubs', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
    op.create_table_comment(
        'certification_levels',
        'Reference table for coach and umpire certification levels',
        existing_comment=None,
        schema=None
    )
    op.drop_index(op.f('ix_certification_levels_id'), table_name='certification_levels')
    op.alter_column('certification_levels', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
    op.alter_column('certification_levels', 'description',
               existing_type=sa.String(length=255),
               type_=sa.TEXT(),
               existing_nullable=True)
    op.alter_column('certification_levels', 'level_type',
               existing_type=sa.VARCHAR(length=20),
               nullable=False)
    op.alter_column('certification_levels', 'level_name',
               existing_type=sa.String(length=50),
               type_=sa.VARCHAR(length=100),
               existing_nullable=False)
    # ### end Alembic commands ###
